epochs:
  value: 400
batch_size:
  value: 32
val_split:
  value: .2
height:
  value: 224
width:
  value: 224
filename:
  value: train_root.csv
model_path:
  value: "saved_models/weights.HUVEC.20190903-075047=284=2.44.hdf5"
controls_only:
  value: False
train_mode:
  desc: Whether to train single image (1), 6 image (2).
  value: 2
cell_type:
  value: HEPG2
locked_layers:
  value: 42
  desc: Conv blocks are each 3 layers each - Conv2D + BatchNorm + Pooling layer.
