epochs:
  value: 200
batch_size:
  value: 16
val_split:
  value: .2
height:
  value: 224
width:
  value: 224
filename:
  value: all_controls_root.csv
model_path:
  value:
controls_only:
  value: True
train_mode:
  desc: Whether to train single image (1), 6 image (2).
  value: 2
cell_type:
  value: U2OS
locked_layers:
  value: 0
  desc: Conv blocks are each 3 layers each - Conv2D + BatchNorm + Pooling layer.
