epochs:
  value: 300
batch_size:
  value: 32
val_split:
  value: .2
height:
  value: 224
width:
  value: 224
filename:
  value: train_root.csv
model_path:
  value:
controls_only:
  value: False
train_mode:
  desc: Whether to train single image (1), 6 image (2).
  value: 2
cell_type:
  value: HUVEC
